exclude: '^$'

fail_fast: false

default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: no-commit-to-branch
      args: [--branch, master, --branch, develop]
    - id: trailing-whitespace
    - id: check-added-large-files
      args: [maxkb=512]
    - id: check-ast
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
    - id: check-xml
    - id: check-yaml
    - id: check-symlinks
    - id: check-merge-conflict
    - id: detect-private-key
    - id: check-executables-have-shebangs
    - id: name-tests-test
      exclude: "^tests/.*[factories.py|datasets.py]"
      args: ['--django']        # uncomment to change tests to 'test_*.py' rather '*_test.py'
    - id: requirements-txt-fixer
    - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.21'
    hooks:
    - id: isort

  - repo: https://github.com/asottile/seed-isort-config
    rev: 'v2.2.0'
    hooks:
    - id: seed-isort-config

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ['--line-length=120']

#   - repo: local
#     hooks:
#       - id: pytest-check
#         name: pytest-check
#         entry: env SLOW_TESTS=False poetry run pytest tests
#         language: system
#         pass_filenames: false
#         always_run: true
